### PR TITLE
Include note about the copy command

### PR DESCRIPTION
**Pull request by RandomEngy**
Added note about running the copy command.

### CODE REVIEW

**Comment by IT-MikeS** [comment]
This would better live in the docs, and the noted requirement to run copy to update the platform with your new web app changes is the same across all capacitor platforms. 

I may make a note in the docs for the next version but for now, platform assumes a base understanding of capacitors functionality, however thank you for your suggestion!

**Comment by RandomEngy** [comment]
I thought it would be helpful to Capacitor users that are trying Electron first, while a minor annoyance to veteran users that don't need to be told that. But OK.

**Comment by RouR** [comment]
I don't agree about "the same across all capacitor platforms".

99% of the time it is used as part of the Ionic.

For Android and Ios, you don't need to use the `npx cap copy` command.
`ionic capacitor run android` is ok.
`ionic capacitor run electron` is failed.

`npx cap copy @capacitor-community/electron` is only necessary for Eleсtron.
And I ran into this problem. It's a good that I looked it up on issues.

This command should be added to the documentation.

**Comment by IT-MikeS** [comment]
> I don't agree about "the same across all capacitor platforms".
> 
> 
> 
> 99% of the time it is used as part of the Ionic.
> 
> 
> 
> For Android and Ios, you don't need to use the `npx cap copy` command.
> 
> `ionic capacitor run android` is ok.
> 
> `ionic capacitor run electron` is failed.
> 
> 
> 
> `npx cap copy @capacitor-community/electron` is only necessary for Eleсtron.
> 
> And I ran into this problem. It's a good that I looked it up on issues.
> 
> 
> 
> This command should be added to the documentation.

I haven't tried this but I believe `ionic capacitor run @capacitor-community/electron` will work but I could be wrong and if so I'll look into a PR for the ionic cli to support capacitor custom platforms

**Pull request closed without merging**
