### PR TITLE
Add useTrayIcon and option trayContextMenu

### PR DESCRIPTION
**Pull request by vevedh**
Add useTrayIcon and option trayContextMenu
if useTrayIcon = true  show Icon in Windows 10 taskBar

### CODE REVIEW

**Comment by vevedh** [comment]
update plungin by plugin

**Comment by IT-MikeS** [comment]
Looks good, but I made a couple of edits to keep the `trayMenu` option more inline with how other options work currently along with not making it enabled by default.

**Comment by IT-MikeS** [comment]
@all-contributors please add @vevedh for code,doc

**Comment by IT-MikeS** [comment]
@all-contributors please add @vevedh for code and doc

**Pull request merged**
